datadir: datadir
seed: 42

# To check configurable parameters, see https://huggingface.co/docs/diffusers/api/models/unet2d
model:
  in_channels: 3
  out_channels: 3
  down_block_types: 
    - "DownBlock2D"
    - "DownBlock2D"
  up_block_types: 
    - "UpBlock2D"
    - "UpBlock2D"
  block_out_channels:
    - 128
    - 256

diffusion:
  num_timesteps: 1000
  noise_schedule: linear
  noise_schedule_kwargs:
    start: 0.0001
    end: 0.02

plot:
  num_samples: [8, 8]
  image_size: [3, 32, 32]
  every_n_epochs: 50

train:
  batch_size: 256
  num_epochs: 1000

optimizer:
  lr: 1e-4
